name: Deploy to Kubernetes (Windows Runner)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl (v1.30.1)
        run: |
          curl.exe -LO https://dl.k8s.io/release/v1.30.1/bin/windows/amd64/kubectl.exe
          mkdir C:\kubectl
          move kubectl.exe C:\kubectl\kubectl.exe
        shell: powershell

      - name: Add kubectl to PATH
        run: |
          echo "C:\kubectl" | Out-File -Append $env:GITHUB_PATH
        shell: powershell

      - name: Set up kubeconfig
        run: |
          mkdir $HOME\.kube
          echo "${{ secrets.KUBE_CONFIG}}" | Out-File -Encoding ascii $HOME\.kube\config.b64
          certutil -decode $HOME\.kube\config.b64 $HOME\.kube\config
        shell: powershell

      - name: Test Kubernetes access
        run: kubectl get pods 
        shell: powershell

