name: ATM CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display greeting
        shell: pwsh
        run: |
          Write-Host "How are you, boy? How is school, done boy?"

      - name: Display current date
        shell: pwsh
        run: |
          Write-Host "Current date is: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
