name: rtgplus

on:
  push:
    branches: [ dev2 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display greeting
        run: echo "How are you boy,ytrfdsfdsgdffdfd how is schoolhgjhkhhggftrret5?"

      - name: Print contents of book.txt
        run: Get-Content ".github/workflows/book.txt"




      